server:
  port: 8080
  servlet:
    context-path: /
# https配置
#  ssl:
#      key-store: classpath:wsriakey
#      key-store-password: 123456
#      key-alias: wsria

spring:
  application:
    name: springboot_mybatis
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    # 页面不缓存
    cache: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  #全局的映射，不用在xml文件写实体类的全路径
  type-aliases-package: com.aws.springboot_mybatis.entity
